name: template node CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    
    steps:
      - uses: actions/checkout@v2

      - name: Yarn CLI
        # You may pin to the exact commit or the version.
        # uses: CultureHQ/actions-yarn@661c6f3a66041c2432bcfb78096b9207304614c8
        uses: CultureHQ/actions-yarn@v1.0.1

      - name: Install librarys
        run: yarn install
      
      - name: Build
        run: yarn run build
      
      - name: Start
        run: yarn start
